pipeline {
    agent {
        label 'node' // This runs the pipeline on a node labeled 'node'
    }
    stages {
        stage('Test') {
    agent {
        docker {
            image 'node:16-alpine'
        }
    }

            steps {
                sh 'node --version'
            }
        }
    }
}
